export const REQUEST_AACHIEVE_DATA = 'REQUEST_AACHIEVE_DATA'
export const SHOW_AACHIEVE_DATA = 'SHOW_AACHIEVE_DATA'
export const FAILED_GET_AACHIEVE_DATA = 'FAILED_GET_AACHIEVE_DATA'
export const SUCCESS_AACHIEVE_DATA = 'SUCCESS_AACHIEVE_DATA'