export const REQUEST_ACCEPTED_DATA = 'REQUEST_ACCEPTED_DATA'
export const SHOW_ACCEPTED_DATA = 'SHOW_ACCEPTED_DATA'
export const FAILED_GET_ACCEPTED_DATA = 'FAILED_GET_ACCEPTED_DATA'
export const SUCCESS_ACCEPTED_DATA = 'SUCCESS_ACCEPTED_DATA'