export const REQUEST_ACHIEVE_DATA = 'REQUEST_ACHIEVE_DATA'
export const SHOW_ACHIEVE_DATA = 'SHOW_ACHIEVE_DATA'
export const FAILED_GET_ACHIEVE_DATA = 'FAILED_GET_ACHIEVE_DATA'
export const SUCCESS_ACHIEVE_DATA = 'SUCCESS_ACHIEVE_DATA'