export const REQUEST_ATHLETE_DATA = 'REQUEST_ATHLETE_DATA'
export const SHOW_ATHLETE_DATA = 'SHOW_ATHLETE_DATA'
export const FAILED_GET_ATHLETE_DATA = 'FAILED_GET_ATHLETE_DATA'
export const SUCCESS_ATHLETE_DATA = 'SUCCESS_ATHLETE_DATA'