export const REQUEST_CATEGORY_DATA = 'REQUEST_CATEGORY_DATA'
export const SHOW_CATEGORY_DATA = 'SHOW_CATEGORY_DATA'
export const FAILED_GET_CATEGORY_DATA = 'FAILED_GET_CATEGORY_DATA'
export const SUCCESS_CATEGORY_DATA = 'SUCCESS_CATEGORY_DATA'