export const REQUEST_INVESTOR_DATA = 'REQUEST_INVESTOR_DATA'
export const SHOW_INVESTOR_DATA = 'SHOW_INVESTOR_DATA'
export const FAILED_GET_INVESTOR_DATA = 'FAILED_GET_INVESTOR_DATA'
export const SUCCESS_INVESTOR_DATA = 'SUCCESS_INVESTOR_DATA'