export const REQUEST_MYAPPLY_DATA = 'REQUEST_MYAPPLY_DATA'
export const SHOW_MYAPPLY_DATA = 'SHOW_MYAPPLY_DATA'
export const FAILED_GET_MYAPPLY_DATA = 'FAILED_GET_MYAPPLY_DATA'
export const SUCCESS_MYAPPLY_DATA = 'SUCCESS_MYAPPLY_DATA'