export const REQUEST_MYSCHOLARSHIP_DATA = 'REQUEST_MYSCHOLARSHIP_DATA'
export const SHOW_MYSCHOLARSHIP_DATA = 'SHOW_MYSCHOLARSHIP_DATA'
export const FAILED_GET_MYSCHOLARSHIP_DATA = 'FAILED_GET_MYSCHOLARSHIP_DATA'
export const SUCCESS_MYSCHOLARSHIP_DATA = 'SUCCESS_MYSCHOLARSHIP_DATA'