export const REQUEST_SCHOLARSHIP_DATA = 'REQUEST_SCHOLARSHIP_DATA'
export const SHOW_SCHOLARSHIP_DATA = 'SHOW_SCHOLARSHIP_DATA'
export const FAILED_GET_SCHOLARSHIP_DATA = 'FAILED_GET_SCHOLARSHIP_DATA'
export const SUCCESS_SCHOLARSHIP_DATA = 'SUCCESS_SCHOLARSHIP_DATA'